# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  run:
    desc: Run API server
    cmds:
      - go run main.go

  build:
    desc: Build API
    cmds:
      - go build -o pukiwiki-migration .

  clean:
    desc: Clean the Binary
    cmds:
      - rm ./pukiwiki-migration

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  migrate:up:
    desc: Migrate up all DB schemas
    cmd: goose -dir db/migrations sqlite3 pukiwiki-migration.db up

  migrate:down:
    desc: Migrate down all DB schemas
    cmd: goose -dir db/migrations sqlite3 pukiwiki-migration.db down
