// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package db

import (
	"context"
)

const createMigration = `-- name: CreateMigration :exec
INSERT INTO migrations (id, pukiwiki_user, notion_page_id, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMigrationParams struct {
	ID           string
	PukiwikiUser string
	NotionPageID string
	Status       string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateMigration(ctx context.Context, arg CreateMigrationParams) error {
	_, err := q.db.ExecContext(ctx, createMigration,
		arg.ID,
		arg.PukiwikiUser,
		arg.NotionPageID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getMigrationByID = `-- name: GetMigrationByID :one
SELECT id, pukiwiki_user, notion_page_id, status, created_at, updated_at
FROM migrations WHERE id = ?
`

func (q *Queries) GetMigrationByID(ctx context.Context, id string) (Migration, error) {
	row := q.db.QueryRowContext(ctx, getMigrationByID, id)
	var i Migration
	err := row.Scan(
		&i.ID,
		&i.PukiwikiUser,
		&i.NotionPageID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMigrationStatus = `-- name: UpdateMigrationStatus :exec
UPDATE migrations
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateMigrationStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateMigrationStatus(ctx context.Context, arg UpdateMigrationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMigrationStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
