// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Migration struct {
	ID           string
	PukiwikiUser string
	NotionPageID string
	Status       string
	CreatedAt    string
	UpdatedAt    string
}

type Page struct {
	ID           string
	PukiwikiUser string
	PukiwikiPage string
	Status       string
	NotionID     string
	ErrorMsg     string
	UpdatedAt    string
}
