// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"
)

const getPendingPages = `-- name: GetPendingPages :many
SELECT pukiwiki_page FROM pages
WHERE pukiwiki_user = ? AND status IN ('pending', 'failed')
`

func (q *Queries) GetPendingPages(ctx context.Context, pukiwikiUser string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPendingPages, pukiwikiUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var pukiwiki_page string
		if err := rows.Scan(&pukiwiki_page); err != nil {
			return nil, err
		}
		items = append(items, pukiwiki_page)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusSummary = `-- name: GetStatusSummary :many
SELECT status, COUNT(*) AS count FROM pages
WHERE pukiwiki_user = ? GROUP BY status
`

type GetStatusSummaryRow struct {
	Status string
	Count  int64
}

func (q *Queries) GetStatusSummary(ctx context.Context, pukiwikiUser string) ([]GetStatusSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatusSummary, pukiwikiUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatusSummaryRow
	for rows.Next() {
		var i GetStatusSummaryRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePageStatus = `-- name: UpdatePageStatus :exec
UPDATE pages
SET status = ?, notion_id = ?, error_msg = ?, updated_at = ?
WHERE pukiwiki_user = ? AND pukiwiki_page = ?
`

type UpdatePageStatusParams struct {
	Status       string
	NotionID     string
	ErrorMsg     string
	UpdatedAt    string
	PukiwikiUser string
	PukiwikiPage string
}

func (q *Queries) UpdatePageStatus(ctx context.Context, arg UpdatePageStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePageStatus,
		arg.Status,
		arg.NotionID,
		arg.ErrorMsg,
		arg.UpdatedAt,
		arg.PukiwikiUser,
		arg.PukiwikiPage,
	)
	return err
}

const upsertPage = `-- name: UpsertPage :exec
INSERT OR IGNORE INTO pages (id, pukiwiki_user, pukiwiki_page, status, updated_at)
VALUES (?, ?, ?, 'pending', ?)
`

type UpsertPageParams struct {
	ID           string
	PukiwikiUser string
	PukiwikiPage string
	UpdatedAt    string
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage,
		arg.ID,
		arg.PukiwikiUser,
		arg.PukiwikiPage,
		arg.UpdatedAt,
	)
	return err
}
